### ISSUE TITLE
Add strong name for 2.0 release

### ISSUE THREAD

**Issue by kolomiets** [MRCollective/NHibernate.SqlAzure#13]
I see that you explicitly stated that you removed strong name in version 2 of the library, but could you please provide any rational explanation why you did so? 

We use this library in a big project and now it is a big pain for us - we need to recompile the library instead of using released NuGet version.

**Comment by robdmoore** [comment]
Closing this issue since it's not something I'm willing to do and there are reasonable alternatives that allow you to work around it without too much fuss e.g. https://github.com/brutaldev/StrongNameSigner#build-process.
