### ISSUE TITLE
Release a new version of the nuget package after the recent changes.

### ISSUE THREAD

**Issue by BishoyDemian** [MRCollective/NHibernate.SqlAzure#18]
After submitting a PR and getting merged, I'm still waiting on a new version of the nuget package to make it to nuget.org.

**Comment by MattDavies** [comment]
Hey @BishoyDemian, sorry this took so long.

We've released [2.1.3](https://github.com/MRCollective/NHibernate.SqlAzure/releases/tag/2.1.3), thanks for the contribution!
