### ISSUE TITLE
Is there any potential issue using MsSqlConfiguration.MsSql2012 instead of MsSqlConfiguration.MsSql2008 with this driver?

### ISSUE THREAD

**Issue by Will-Bill** [MRCollective/NHibernate.SqlAzure#19]
As per the title, is there any issue using the MsSqlConfiguration.MsSql2012 configuration for SQL Azure?

From what I understand, SQL azure supports the features of 2012 re paging - and having tested it seems to be fine but want to know if I was missing something.

**Comment by robdmoore** [comment]
There shouldn't be a problem with that configuration to my knowledge, but it's been a while since I've used NHibernate.

Do you need a change to NHibernate.SqlAzure? If so feel free to submit a PR.

**Comment by Will-Bill** [comment]
Thanks for getting back to me.

Don't think there is any need to PR, as it seems to be working. Just in the docs it specifies 2008 but I assume that is just because 2012 wasn't out when written.

**Comment by robdmoore** [comment]
Do ou mind sending a PR to fix the docs?

--
Rob Moore | Readify Principal Consultant, Technical Specialist (Microsoft Azure) | m +61 400 777 763 | e rob.moore@readify.net | w readify.net
