### ISSUE TITLE
Nuget package for NH 4.1.x

### ISSUE THREAD

**Issue by RogerKratz** [MRCollective/NHibernate.SqlAzure#20]
Hi

Would be nice with a nuget package targeting NH 4.1.x (recently released) so we don't have to use assembly redirects.

Thanks
Roger

**Comment by robdmoore** [comment]
Does the package work with NH 4 with binding redirects?

I'm happy to accept a pull request with that upgrade :)

--

**Comment by RogerKratz** [comment]
Done here
https://github.com/MRCollective/NHibernate.SqlAzure/pull/21

Unfortunatly I needed to checkout code I didn't want to - needed to run test against sql server rather than sql express that seems to be hard coded in current test code base. Hopefully discard correct file changes in the end though...
