### ISSUE TITLE
Exception during Configuration.BuildSessionFactory() when the package is used with NH 4.1.0.4000

### ISSUE THREAD

**Issue by alobakov** [MRCollective/NHibernate.SqlAzure#22]
I'm trying to use this package with NH 4.1.0.4000, but am getting the following exception during Configuration.BuildSessionFactory():

**Could not load type 'NHibernate.SqlAzure.ReliableSqlDbConnection' from assembly 'NHibernate.SqlAzure, Version=2.1.4.0, Culture=neutral, PublicKeyToken=null' because the method 'GetSchema' has no implementation (no RVA).**

Stack trace:

   at NHibernate.SqlAzure.ReliableSql2008ClientDriver.CreateConnection()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare()
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactory sessionFactory)
   at NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners)
   at NHibernate.Cfg.Configuration.BuildSessionFactory()

The factory is being configured as follows:

```
	var config = new Configuration();

	config.DataBaseIntegration(p =>
	{
		p.ConnectionProvider<RootConnectionProvider>();
		p.Dialect<NHibernate.Dialect.MsSql2012Dialect>();
		p.Driver<NHibernate.SqlAzure.SqlAzureClientDriver>();
		p.IsolationLevel = System.Data.IsolationLevel.ReadCommitted;
		p.TransactionFactory<NHibernate.Transaction.AdoNetTransactionFactory>();
	});

	config.AddAssembly(Assembly.GetExecutingAssembly());

	sessionFactory = config.SetInterceptor(new AuditingInterceptor()).BuildSessionFactory();
```
As a side note, RootConnectionProvider is very simple:

```
	public class RootConnectionProvider : DriverConnectionProvider
	{
		protected override string ConnectionString
		{
			get
			{
				return <connection string>;
			}
		}

		public override void Configure(IDictionary<string, string> settings)
		{
			ConfigureDriver(settings);
		}
	}

```

The code is executing in an ASP.NET Core 1.1.0 application targeting .NET 4.6.1. 
I was initially using the NHibernate.SqlAzure package which produced the same exception, then found the note about NH4 on nuget.org and upgraded to NHibernate4.SqlAzure. But the problem persists even after manually deleting all the obj/bin folders in the solution and rebuilding from scratch. 
Any idea what might be at play here?

**Comment by alobakov** [comment]
Just re-tested this with NHibernate4.SqlAzure.Standalone, - no such issue there.

**Comment by robdmoore** [comment]
What version of the package are you using?

@RogerKratz do you have any ideas about this?

**Comment by alobakov** [comment]
NHibernate4.SqlAzure 2.1.4 is the one producing this exception
NHibernate4.SqlAzure.Standalone 2.1.4 works just fine, so I'd assume this could be an IL-merge issue of some kind.

**Comment by RogerKratz** [comment]
If replacing the dll from nuget with a manually compiled one, it seems to work. 
@robdmoore, what is your "release procedure"? Is it possible you missed something there?

**Comment by robdmoore** [comment]
Ahh I've found the problem. Looks like when you compile using Roslyn (that would have changed when @MattDavies recently updated our build server to VS2017 RC) and you use Roslyn then this error occurs.

https://github.com/Microsoft/CodeContracts/issues/53

Looks like we should be able to update ILMerge to fix it.

Does one of you mind updating the version of ILMerge and changing the reference of it in NHibernate4.SqlAzure.csproj and NHibernate.SqlAzure.csproj to reference the correct version?

**Comment by RogerKratz** [comment]
Done
https://github.com/MRCollective/NHibernate.SqlAzure/pull/23

**Comment by RogerKratz** [comment]
@robdmoore Ping ;). Was this what you needed?

**Comment by robdmoore** [comment]
I'll release the new version to nuget now.

I'd appreciate someone reporting back if this problem is fixed :)

**Comment by alobakov** [comment]
Verified-tested. - Thanks guys!

**Comment by robdmoore** [comment]
Excellent!

**Comment by RogerKratz** [comment]
@robdmoore Can you please release a new version of NHibernate4.SqlAzure (2.1.5) as well?

**Comment by robdmoore** [comment]
I thought I already released the latest - did I forget something?

**Comment by RogerKratz** [comment]
@robdmoore 
You released 2.1.5 for
https://www.nuget.org/packages/NHibernate.SqlAzure/
but not for (which is targeting NH4 I guess?)
https://www.nuget.org/packages/NHibernate4.SqlAzure.Standalone/
which we are using in our project

Thanks
Roger

**Comment by RogerKratz** [comment]
Sorry, I meant
https://www.nuget.org/packages/NHibernate4.SqlAzure/
(without StandAlone)

**Comment by robdmoore** [comment]
Weird. That's not intentional. The Ci server should have released everything. I'll take a look why.

--

**Comment by RogerKratz** [comment]
Ok, thanks.

**Comment by robdmoore** [comment]
Fixed now - manually uploaded hte packges. Can't see why it didn't work on the CI server - it's configured correctly.

**Comment by RogerKratz** [comment]
Thanks!
