### ISSUE TITLE
Possible support for very old NHibernate versions

### ISSUE THREAD

**Issue by felixg** [MRCollective/NHibernate.SqlAzure#24]
Hello,
I've an old project circa ~2011 that uses .NET 3.5 and NHibernate 2.1.2.4000 (minor part uses Enterprise Library 3.1). It's un-upgradeable because some external dependencies aren't supported any more. We're investigating possible migration to Azure, preferably in a non-VM fashion. Is it possible in some way (maybe via an old version) to use NHibernate.SqlAzure with a such old configuration? If not directly, can you estimate the work required?

**Comment by ghuntley** [comment]
@felixg the maintainers will not be able to provide an estimate as your employer not upgrading software and expecting an unpaid open-source community to support it is unreasonable. Most maintainers are happy to engage (in private) with users to aide with specialized circumstances such as this but commercial terms are typically measured in weeks.

**Comment by felixg** [comment]
I'm not expecting anything, just wondering if someone has done it before or can point to the right direction - The same way I've helped in multiple OSS projects during the last decade. It's not unreasonable to research the possibilities before jumping to implement it yourself.

**Comment by robdmoore** [comment]
The code that bridges between the reliable `IDbConnection` code and the NHibernate world is actually really small. See the `ReliableSql2008ClientDriver` class. Assuming the old version of NHibernate supports client drivers you can probably pull it off.

This isn't something that makes sense to do for this library so closing this issue.
