### ISSUE TITLE
Support for latest version of NHibernate

### ISSUE THREAD

**Issue by RogerKratz** [MRCollective/NHibernate.SqlAzure#28]
..would be great!

**Comment by wendelstam** [comment]
Any updates around this? Or are there any other workarounds anybody can tip about.

**Comment by robdmoore** [comment]
You might be able to get away with binding redirects. If not then feel free to submit a PR with the update.

--

**Comment by icecoldfire** [comment]
Binding redirects doesn't work, there is an PR so any updates?

**Comment by praga** [comment]
Same here, any updates on the PR

**Comment by robdmoore** [comment]
Just commented on the PR - looks like it's got some build errors.

If someone can get a PR up that upgrades to latest version I'm happy to merge and release.

**Comment by robdmoore** [comment]
This has now been released to nuget. Thanks to @jaykay-design!
